### ISSUE TITLE
Ошибка при конвертации PNG

### ISSUE THREAD

**Issue by luiswoo** [gil9red/compress_image_fb2#3]
Fedora 37. В консоле:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/media_lin/Документы/Программы/compress_image_fb2-master/compress_image_fb2.py", line 82, in compress_image_fb2
    im.save(jpeg_buffer, format='jpeg')
  File "/usr/lib64/python3.11/site-packages/PIL/Image.py", line 2320, in save
    save_handler(self, fp, filename)
  File "/usr/lib64/python3.11/site-packages/PIL/JpegImagePlugin.py", line 632, in _save
    raise OSError(f"cannot write mode {im.mode} as JPEG") from e
OSError: cannot write mode RGBA as JPEG
    27. i_026.jpg. Compress: 65%
        98.9KiB --> 34.4KiB
        768x1024 --> 384x512
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/PIL/JpegImagePlugin.py", line 630, in _save
    rawmode = RAWMODE[im.mode]
              ~~~~~~~^^^^^^^^^
KeyError: 'RGBA'
```
На Флибусте предложили исправление http://flibusta.is/comment/3485484:
«https://stackoverflow.com/questions/48248405/cannot-write-mode-rgba-as-jpeg

Попробуйте:
```
                # Конверируем в JPG
                jpeg_buffer = io.BytesIO()
                im = im.convert('RGB')
                im.save(jpeg_buffer, format='jpeg')
                compress_im_data = jpeg_buffer.getvalue()
```
«Но не факт что будет нормально ибо "In most cases the discarding the alpha channel will give you undesirable result, because transparent pixels also have some unpredictable colors. It is much better to fill transparent pixels with certain color"»

На данный момент явных проблем не выявлено.

**Comment by luiswoo** [comment]
ps При конвертации ещё выводится предупреждение: 
```
compress_image_fb2.py:102: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  resized_im = compress_im.resize((width, height), Image.ANTIALIAS)
    1. img_0.png. Compress: 39%
        PNG --> JPEG
        28.1KiB --> 17.1KiB
        1920x1080 --> 960x540
```

**Comment by luiswoo** [comment]
pps Дополнение с Флибусты относительно цвета фона:
«
```
                # Конверируем в JPG
                jpeg_buffer = io.BytesIO()
                if im.mode in ('RGBA', 'LA'):
                    background = Image.new('RGB', im.size, 'white')
                    background.paste(im, im.split()[-1])
                    im = background
                im.save(jpeg_buffer, format='jpeg')
                compress_im_data = jpeg_buffer.getvalue()
```
Не пробовал, нет питона :) Цвет фона - white, можно поменять.

Если хочется поменять качество сжатия то добавьте параметр im.save(jpeg_buffer, format='jpeg', quality=95)»

**Comment by luiswoo** [comment]
В общем тут https://github.com/luiswoo/compress_image_fb2/blob/master/compress_image_fb2.py в лоб было заменено Image.ANTIALIAS на Image.Resampling.LANCZOS и были внесены все изменения, предложенные на Флибусте.

**Comment by gil9red** [comment]
Спасибо за исправление :)
Я этот проект давно не поддерживаю, но у вас есть его форк и с изменениями, а значит можете сделать pull request, который могу принять и ваш коммит попадет сюда

А насчет Image.ANTIALIAS - поменять на рекомендуемое, в предупреждении, значение

Кст, у вас, похоже, не Pillow == 8.3.2 стоит (он указан в requirements.txt), тогда по-крайней мере, не было бы предупреждения с Image.ANTIALIAS и возможно той ошибки с RGBA :)

**Comment by luiswoo** [comment]
Не имею представления, как это делать. 
В Федоре актуальные версии: Python — 3.11.3, Pillow — 9.2.0. У второго питона, что стоит для совместимости, не оказалось какой-то библиотеки.
Проблеме с png около года, просто на Author Today начали активней этот формат использовать — ну как Midjourney со Stable Diffusion освоили, так и стали клепать файлы на десятки мегабайт. Точнее софтина вытягивает изображения при создании fb2 откуда-то со стороны на десятки мегабайт.

**Comment by luiswoo** [comment]
Сделан сей пулреквест, надеюсь корректно.

**Comment by gil9red** [comment]
Переделал скрипт с новым API - 8a84e30e114b7a7d0b3ddb4a7c7ada4408b3ac5c
