### ISSUE TITLE
Ошибка при сохранении файлов с расширением jpg

### ISSUE THREAD

**Issue by luiswoo** [gil9red/compress_image_fb2#5]
Не уверен, что точно этот выхлоп:
`KeyError: 'JPG'
Traceback (most recent call last):
  File "/home/user/media_lin/Документы/Программы/compress_image_fb2-master/compress_image_fb2.py", line 108, in compress_image_fb2
    resized_im.save(resize_buffer, format=short_content_type)
  File "/usr/lib64/python3.11/site-packages/PIL/Image.py", line 2418, in save
    save_handler = SAVE[format.upper()]
`
Но жаловалось на эту строку `resized_im.save(resize_buffer, format=short_content_type)`.
По подсказке https://stackoverflow.com/questions/37048807/python-image-library-and-keyerror-jpg методом научного тыка, было заменено на `resized_im.save(resize_buffer, format = 'JPEG' if short_content_type.lower() == 'jpg' else short_content_type.upper())` Но вот не факт, что это правильно, пусть скрипт и работает.

**Comment by gil9red** [comment]
Переделал скрипт с новым API, попутно исправив эту ошибку в 8a84e30e114b7a7d0b3ddb4a7c7ada4408b3ac5c
